### ISSUE TITLE
Error when using email to generate cert

### ISSUE THREAD

**Issue by tezwork** [patrickpr/YAOG#7] opened 2020-07-15 21:24 UTC
I get a string error when using a email similar to it.alerts@testdomain.org.nz

Error:
"Lib : asn1 encoding routines, doing : ASN1_mbstring_ncopy, reason : string too long (13/122/151)"

I can generate without the email which is fine, but frustrating.

**Comment by patrickpr** [comment] 2020-07-16 08:53
Hi,

I'll have a look at this. Please give me the following info : 

- Yaog & Operating system version
- Do you have this error when generating self signed cert or CSR ?

Regards,

**Comment by patrickpr** [comment] 2020-07-17 14:39
I managed to reproduce the bug, will be working on soon.

**Comment by patrickpr** [comment] 2020-07-21 19:41
Hi,

Looking at the [RFC5280](https://tools.ietf.org/html/rfc5280#appendix-A.1) page 123, the common name should be less than 64 caracters ("ub" is for upper bound) : "ub-common-name INTEGER ::= 64"

Common name (CN) is composed of : 
1) The certificate name (can be URL but also something else)
2) if an email is provided, then the string "/emailAddress=\<email\>" is added to it.

If length of name + email + "/emailAddress=" is more than 64 caracters then it leads to an error.

This seems to be harcoded in OpenSSL and for good reasons as the RFC says : "specifications of Upper Bounds MUST be regarded as mandatory", so any certificate with more than 64 caracters in CN will be invalid.

I suggest you put a short name in the "name (CN)", set the email and add the real URL as a SubjectAltName (click "add" in the X509 extensions box ans choose SubjectAltName ).

/Patrick

**Comment by patrickpr** [comment] 2020-08-25 16:32
Feel free to open the case again if you have comments or questions regarding this.

**Closed by patrickpr** 2020-08-25 16:32 UTC
Labels: question
